// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import { type Infer as __Infer } from "spacetimedb";

// Import all reducer arg schemas
import CreateTimerCounterReducer from "../create_timer_counter_reducer";
import DeleteTimerCounterReducer from "../delete_timer_counter_reducer";
import UpdateTimerCounterReducer from "../update_timer_counter_reducer";

export type CreateTimerCounterParams = __Infer<typeof CreateTimerCounterReducer>;
export type DeleteTimerCounterParams = __Infer<typeof DeleteTimerCounterReducer>;
export type UpdateTimerCounterParams = __Infer<typeof UpdateTimerCounterReducer>;

