// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const AuthLog = __t.object("AuthLog", {
  id: __t.u64(),
  owner: __t.identity(),
  clientTs: __t.string(),
  event: __t.string(),
  detail: __t.string(),
});
export type AuthLog = __Infer<typeof AuthLog>;

export const TimerCounter = __t.object("TimerCounter", {
  id: __t.u64(),
  owner: __t.identity(),
  label: __t.string(),
  currentCount: __t.i32(),
  remainingTimeSeconds: __t.u32(),
  timerState: __t.string(),
  timerStartedAtMs: __t.u64(),
});
export type TimerCounter = __Infer<typeof TimerCounter>;

